# Generated by Django 3.2.8 on 2022-01-20 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='computer',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comps.class', verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='computer',
            name='count',
            field=models.CharField(default='0', max_length=10, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='computer',
            name='model',
            field=models.CharField(max_length=50, null=True, verbose_name='Модель'),
        ),
    ]
